apiVersion: apps/v1
kind: Deployment
metadata:
  name: intweb-deployment
spec:
  selector:
    matchLabels:
      app: intweb-app
  replicas: 1
  template:
    metadata:
      labels:
        app: intweb-app
    spec:
      containers:
      - name: intweb
        image: tamirzamo/devops:intweb_{{version}}
        ports:
        - containerPort: 50000